"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var point_1 = require("./point");
var myPoint = new point_1.Point(3, 4);
console.log("toString():", myPoint.toString());
myPoint.setX(5);
myPoint.setY(-2);
console.log("Nuevas coordenadas:", myPoint.toString());
console.log("getX():", myPoint.getX());
console.log("getY():", myPoint.getY());
console.log("Distancia al origen:", myPoint.distanceToOrigin());
var anotherPoint = new point_1.Point(1, 1);
console.log("Distancia a otro punto (1,1):", myPoint.calculateDistance(anotherPoint));
console.log("Cuadrante:", myPoint.calculateQuadrant());
var pointsArray = [new point_1.Point(0, 0), new point_1.Point(10, 10), new point_1.Point(5, -1)];
var nearest = myPoint.calculateNearest(pointsArray);
console.log("Punto más cercano:", nearest.toString());
