"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Vector_1 = require("./Vector");
var vector1 = new Vector_1.Vector(5, 10);
var vector2 = new Vector_1.Vector(5, 10);
console.log("Vector 1:");
vector1.print();
console.log("Vector 2:");
vector2.print();
var addedVector = vector1.add(vector2);
console.log("Suma de Vector 1 y Vector 2:");
addedVector.print();
var subtractedVector = vector1.subs(vector2);
console.log("Resta de Vector 1 y Vector 2:");
subtractedVector.print();
var multipliedVector = vector1.mult(vector2);
console.log("Producto de Vector 1 y Vector 2:");
multipliedVector.print();
var scaledVector = vector1.multNumber(3);
console.log("Vector 1 multiplicado por 3:");
scaledVector.print();
